version: "3.7"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    << : *restart_policy
    image:
      postgres:
    image: postgres:13-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: monty
      POSTGRES_PASSWORD: monty
      POSTGRES_USER: monty
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monty"]
      interval: 2s
      timeout: 1s
      retries: 5

  redis:
    << : *restart_policy
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    command:
      --save 60 1
    volumes:
      - /docker/host/monty-redis:/data

  snekbox:
    << : *restart_policy
    image: ghcr.io/onerandomusername/snekbox:latest
    hostname: snekbox
    privileged: true
    ports:
     - "8060:8060"
    init: true
    ipc: none
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - user-base:/snekbox/user_base

  monty:
    << : *restart_policy
    image: ghcr.io/onerandomusername/monty-python:latest
    container_name: monty-python
    init: true
    tty: true

    depends_on:
      - postgres
      - redis
    
    environment:
      - REDIS_URI=redis://redis:6379
      - DB_BIND=postgresql://monty:monty@postgres:5432/monty
      - USE_FAKEREDIS=false
      - SNEKBOX_URL=http://snekbox:8060/

    env_file:
      - .env

    volumes:
      - .:/bot

volumes:
  user-base:
